### PR TITLE
Cleanup: Remove duplicate demos

### PR DESCRIPTION
**Pull request by jenny-s51**
**This is a cleanup PR. Please do not review/merge until #19 #20 #21 #22 #25 are all merged**

This PR cleans up any references to "composable" tables - once all deprecated table component instances have been removed and converted to new composable table instances, the existing "composable" demos either become duplicates or obsolete. 

In this PR:

- Removed the existing "Using composable table components" from the Virtualized table examples in favor of the changes in #19 which will use the composable table
- Replaced the file referenced by the default Window Scroller demo (which used deprecated table components) to the composable example file

Towards #14 and #17.

### CODE REVIEW

**Review by wise-king-sullyman — APPROVED** [review]
Rebased, switched target branch to v6 to match the other PRs, fixed a few type issues, other than that everything LGTM!

**Review by dlabaj — APPROVED** [review]
LGTM

**Review by jenny-s51 — COMMENTED** [review]
Thank you @wise-king-sullyman for rebasing and fixing up the remaining TS issues.

I pulled this down and added a couple fixes to the WindowScroller example as discussed, otherwise this looks good to merge! 🚀

**Review by wise-king-sullyman — APPROVED** [review]
🔥

**Pull request merged**
